stages:
  - build
  - deploy

build_izr_screen:
  stage: build
  image: node:alpine
  script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    # Decode and save the SSH key
    - cat $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Configure SSH to disable host key checking
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - git config --global user.email "ci-runner@izr-cloud.online"
    - git config --global user.name "IZR CI Runner"
    - npm install
    - npm run build
    - find deploy -type f ! -name 'Dockerfile' ! -name 'Makefile' ! -name 'nginx.conf' -delete
    - mv dist/* deploy/
    - git config --global user.email "ci-runner@localhost"
    - git config --global user.name "CI Runner"
    - git add deploy/
    - git commit -m "Deploy built content to main"
    - git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/islamic-center-rgbg/izr-screen.git
    - git push origin main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy_izr_screen:
  stage: deploy
  variables:
    TARGET: screen
  trigger:
    include: 
      - project: izr-production/izr-server
        file: .gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'