/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RamadanRouteImport } from './routes/ramadan'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as IzrRouteImport } from './routes/izr'
import { Route as EidMubarakRouteImport } from './routes/eid-mubarak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoPhoneCountdownRouteImport } from './routes/no-phone.$countdown'

const RamadanRoute = RamadanRouteImport.update({
  id: '/ramadan',
  path: '/ramadan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const IzrRoute = IzrRouteImport.update({
  id: '/izr',
  path: '/izr',
  getParentRoute: () => rootRouteImport,
} as any)
const EidMubarakRoute = EidMubarakRouteImport.update({
  id: '/eid-mubarak',
  path: '/eid-mubarak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoPhoneCountdownRoute = NoPhoneCountdownRouteImport.update({
  id: '/no-phone/$countdown',
  path: '/no-phone/$countdown',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eid-mubarak': typeof EidMubarakRoute
  '/izr': typeof IzrRoute
  '/problem': typeof ProblemRoute
  '/ramadan': typeof RamadanRoute
  '/no-phone/$countdown': typeof NoPhoneCountdownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eid-mubarak': typeof EidMubarakRoute
  '/izr': typeof IzrRoute
  '/problem': typeof ProblemRoute
  '/ramadan': typeof RamadanRoute
  '/no-phone/$countdown': typeof NoPhoneCountdownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eid-mubarak': typeof EidMubarakRoute
  '/izr': typeof IzrRoute
  '/problem': typeof ProblemRoute
  '/ramadan': typeof RamadanRoute
  '/no-phone/$countdown': typeof NoPhoneCountdownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eid-mubarak'
    | '/izr'
    | '/problem'
    | '/ramadan'
    | '/no-phone/$countdown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eid-mubarak'
    | '/izr'
    | '/problem'
    | '/ramadan'
    | '/no-phone/$countdown'
  id:
    | '__root__'
    | '/'
    | '/eid-mubarak'
    | '/izr'
    | '/problem'
    | '/ramadan'
    | '/no-phone/$countdown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EidMubarakRoute: typeof EidMubarakRoute
  IzrRoute: typeof IzrRoute
  ProblemRoute: typeof ProblemRoute
  RamadanRoute: typeof RamadanRoute
  NoPhoneCountdownRoute: typeof NoPhoneCountdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ramadan': {
      id: '/ramadan'
      path: '/ramadan'
      fullPath: '/ramadan'
      preLoaderRoute: typeof RamadanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izr': {
      id: '/izr'
      path: '/izr'
      fullPath: '/izr'
      preLoaderRoute: typeof IzrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eid-mubarak': {
      id: '/eid-mubarak'
      path: '/eid-mubarak'
      fullPath: '/eid-mubarak'
      preLoaderRoute: typeof EidMubarakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-phone/$countdown': {
      id: '/no-phone/$countdown'
      path: '/no-phone/$countdown'
      fullPath: '/no-phone/$countdown'
      preLoaderRoute: typeof NoPhoneCountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EidMubarakRoute: EidMubarakRoute,
  IzrRoute: IzrRoute,
  ProblemRoute: ProblemRoute,
  RamadanRoute: RamadanRoute,
  NoPhoneCountdownRoute: NoPhoneCountdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
