name: Notify Parent Repo

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify parent repo to update submodule
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/medaminbl97/izr-server/dispatches \
            -d '{"event_type":"update-submodule","client_payload":{"submodule":"screen"}}'
