name: Build Screen App and Push Docker Image

on:
  push:
    branches:
      - "**" # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (to build React app)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies and build React app
      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: |
          npm run build
          mkdir -p deploy
          cp -r dist/* deploy/
          cp .nginx/* deploy/

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Auto-increment version
      - name: Get version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Current version: $VERSION"

          # Auto increment patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/izr-screen:${{ steps.version.outputs.version }} ./deploy
          docker tag ${{ secrets.DOCKER_USERNAME }}/izr-screen:${{ steps.version.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/izr-screen:latest

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-screen:${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-screen:latest
